# Python Bootcamp (oDCM)

*After installing Anaconda and going over the first 3 chapters of the [Introduction to Python](https://learn.datacamp.com/courses/intro-to-python-for-data-science) DataCamp course, you should have a understanding of variables, lists, and functions. Therefore, we assume you know how to load a Jupyter Notebook and perform basic operations in Python. In this tutorial, we fill in the gaps of knowledge required for web scraping and APIs purposes.*

--- 

## Learning Objectives

Students will be able to: 
* Apply conditional logical using if-else statements
* Define and add items to a dictionary
* Loop over a list of elements 
* Write functions using parameters
* Handle common error messages and debug code
* Read and write text files 

--- 

## Acknowledgements
This course draws on a variety of online resources which can be retrieved from the [course website](https://odcm.hannesdatta.com/#student-profile--prerequisites). 


--- 

## Support Needed?
For technical issues outside of scheduled classes, please check the [support section](https://odcm.hannesdatta.com/docs/course/support) on the course website.

---

## 1. Conditional Logic

### 1.1 Comparison Operators
**Importance**  
In one of the very first Datacamp exercises you were asked to assign the value `100` to a variable `savings` with the statement `savings = 100`. In practice, you oftentimes find yourself in a situation where you want to make a decision based on whether something is true or false. For example, if we reach a negative account balance (`balance < 0`) we want to transfer money from our savings account to our checking account. 

In Python we can make such comparisons with logical operators like you have seen before in your math classes: 

| Operator | Example | What it does | 
| :--- | :--- | :--- |
| > | `a > b` |  Truthy if **a** is greater than **b** |
| < | `a < b` | Truthy if **a** is less than **b** |
| >= | `a >= b` | Truthy if **a** is greater than or equal to **b** |
| <= | `a <= b` | Truthy if **a** is less than or equal to **b** |



**Let's try it out!**

Now assume both `a` and `b` take on the value `1`. Before running the cell below, try to evaluate whether each of the four value (`>`, `<`, `>=`, `<=`) translate into a `True` or `False` value (also known as booleans). 

In [7]:
a = 1 
b = 1
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

False
False
True
True


Rather than looking for values greater or smaller than, we can also check whether items take on the same value (`a == b`) or a different value (`a != b`). Note the difference between variable assignment (single `=`) and the comparison operator (double `==`). For example, `savings = 100` means we create a new variable that we assign a value of `100`, whereas `savings == 100` checks whether the variable already contains a value of `100` (if not it will return `False`). 

In [9]:
savings = 100 # variable assignment
print(savings == 100) # comparison 
print(savings != 100) # comparison (False because it is 100!)

True
False


### 1.2 If-statements

**Importance**  
We can use these comparison operators as inputs for if-statements which tell the computer to choose a different path based on the some type of comparison: 

First, it checks whether the first condition is met (`if some condition`). If not, it will move on to the next line (`elif some condition`). If neither of those conditions are true, it will `do something` according to the `else` clause.

In the bank account example, our program could look like this:

In [16]:
if balance < 0: 
    print("You should top up your checking account to avoid paying interest")
elif balance == 0: 
    print("Your checking account balance is exactly €0.00, be careful when making new payments!")
else: 
    print("You have a positive balance")

You should top up your checking account to avoid paying interest


A few remarks:   
* After each comparison there is a colon (`:`). This tells the program that it's the end of the comparison.  
* The statement below each if, elif, else clause needs to be indented (that is, a TAB or 4 spaces to the right). This improves structure and readability. 
* There can be multiple `elif` statements. For example, if you want to display another message when the balance is positive though very low (e.g., `balance < 50`).
* Note how we can derive that the `balance` must be positive from the fact that it is neither negative (`balance < 0`) nor equal to zero (`balance == 0`).

**Let's try it out!**  
Add a variable `balance` to the top of the cell and assign it a value of `-10` and run the cell. Now do it again and change the value to `0` and `10`. Does the output match your expectations? 

**Exercise 1**  
Say that we want to develop a program that advises students on whether they can take the Online Data Collection and Management course. On the [course catalogue](https://catalogus.tilburguniversity.edu/osiris_student_tiuprd/OnderwijsCatalogusKiesCursus.do) page we find that the course is instructed to Marketing Analytics students. Furthermore, Research Master students can audit this course upon approval of the instructor. 

Use conditional logical to write a program that checks the value of a variable `study` and prints one of the following statements: 
* *You satisfy the course requirements* (for Marketing Analytics students)
* *Please send an email with your motivation to enroll in the course to Hannes Datta* (for Research Master students)
* *You do not satisfy the course requirements. Please contact your educational officer if you want to enroll in the course.* (for all other studies, e.g. "Psychology")

In [ ]:
# your code goes here!

In [18]:
# solution
if study == "Marketing Analytics":
    print("You satisfy the course requirements")
elif study == "Research Master":
    print("Please send an email with your motivation to enroll in the course to Hannes Datta")
else:
    print("You do not satisfy the course requirements. Please contact your educational officer if you want to enroll in the course.")

You satisfy the course requirements


### 1.3 And / Or Operators

**Importance**  
In reality, you may want to check for multiple conditions. For example, employers with a full-time job go to their work every workday provided that it's not a holiday. In other words, both conditions must be met (`and`). Alternatively, you can check if at least one of the conditions is satisfied (`or`). For example, you go to bed if you're tired or whether it's bedtime already. Lastly, you may require a value to be NOT true, for example workers go to work during workdays not during the weekend (`not`). 


| Operator | Example | What it does | 
| :--- | :--- | :--- |
| and | if workday and no_holiday: <br> &nbsp;&nbsp;&nbsp;&nbsp;print("Go to work!") | Truthy if both `workday` and `no_holiday` are true |
| or | if tired or bed_time: <br> &nbsp;&nbsp;&nbsp;&nbsp;print("Go to sleep!") | Truthy if either `tired` or `bed_time` is true (or both) |
| not | if not weekend: <br> &nbsp;&nbsp;&nbsp;&nbsp;print("Go to work!") | Truthy if the opposite is true |

**Let's try it out!**  
Change the boolean values (from `True` to `False` and vice versa), and see how it affects the output! Note that there's no need to write `if workday == True` (`if workday` is shorter and preferred).

In [20]:
workday = True
no_holiday = True

if workday and no_holiday:
    print("Go to work!")

Go to work!


In [22]:
tired = True
bed_time = False

if tired or bed_time:
    print("Go to sleep!")

Go to sleep!


In [21]:
weekend = False

if not weekend:
    print("Go to work!")

Go to work!


**Exercise 2**  
In addition to the study program, the oDCM [course catalogue](https://catalogus.tilburguniversity.edu/osiris_student_tiuprd/OnderwijsCatalogusKiesCursus.do) page also describes that students are expected to have acquired a working knowledge in Python. Extend your program of Exercise 1 such that it not only checks whether students have the right study program, but also the required `prior_knowledge` (boolean variable).

In [ ]:
# solution (it's not necessary to check whether prior_knowledge == True)
if study == "Marketing Analytics" and prior_knowledge:
    print("You satisfy the course requirements")
elif study == "Research Master" and prior_knowledge:
    print("Please send an email with your motivation to enroll in the course to Hannes Datta")
else:
    print("You do not satisfy the course requirements. Please contact your educational officer if you want to enroll in the course.")

Once you chain `and` and `or` statements things become more complex. Suppose that we want to calculate whether a student passed the course or not. As mentioned in the grading criteria, students pass the course if the total course grade is >= 5.5, and the exam is passed (>= 5.5). Since the student scored a 4.3 in her first attempt, she needed to take the resit for which she scored a 5.6. Still, her final grade was only a 5.4 because her team did not do really well in the team project. 

According to the grading criteria, she therefore did not pass the course. Yet the boolean expression below evaluates to `True`, why is that? 

In [28]:
final_grade = 5.4
exam_grade = 4.3
resit_grade = 5.6

final_grade > 5.5 and exam_grade > 5.5 or resit_grade > 5.5

True

Python implicitly evaluates the code from left to write which implies that: 
* The final grade and the exam grade must be greater than or equal to 5.5
* OR the resit grade must be greater than or equal to 5.5 (regardless of the final grade)

We can fix this by explicitly enforcing the structure of the comparisons with parentheses:

In [29]:
final_grade > 5.5 and (exam_grade > 5.5 or resit_grade > 5.5)

False

**Exercise 3**  
The minimum age for driving in the Netherlands is 17, but you cannot get a full license until the age of 18. In between 17 and 18 you need to be accompanied by a coach (e.g., parent who sits next to you in the car). 

The code snippet below should reflect this policy but currently has some issues. Add parentheses to the conditional expressions below such that it adheres to the policy.

In [38]:
driver_license = False
age = 17
coach = True

if driver_license and age >= 18 or age == 17 and coach: 
    print("You're allowed to drive!")    
else: 
    print("You're not allowed to drive!")    

You're allowed to drive!


In [39]:
# solution
if driver_license and (age >= 18 or age == 17 and coach): 
    print("You're allowed to drive!")    
else: 
    print("You're not allowed to drive!")      

You're not allowed to drive!


### 1.4 Wrap-up
Congrats! You've just learned the basics of conditional logic which forms the foundation of any programming language and is a powerful tool. As a programmer, it not only gives you control over what happens under which conditions but it's also incredibly helpful in the later stages of data collection and management (e.g., filtering down on rows).

---
## 2. Dictionaries

### 2.1 Creating Dictionaries
**Importance**  
Previously, we looked at the following list of lists (only the first 2 students are shown): 

In [113]:
students_list = [["Lotte", "Marketing Analytics", True], 
            ["Joep", "Research Master", True]]

One of the major limitations of lists is that it's unclear what each item is (e.g., we have no clue what the `True` and `False` values mean without context). Ideally, we'd like to assign these values a label to encode more information than only the order. A dictionary (`{}`) is a data structure that consists of key value pairs and thus addresses this need. The keys describe the data (labels) and the values represent the data itself. 

Keys and values are separated by a colon, and we denote the next item with a comma (just like a list). Here's the data of the first student converted into a dictionary: 

In [120]:
student_dict = {"name": "Lotte", 
                "study": "Marketing Analytics", 
                "prior_knowledge": True}

print(student_dict)

{'name': 'Lotte', 'study': 'Marketing Analytics', 'prior_knowledge': True}


**Let's try it out!**   
Add another key to `student_dict` that stores the age of Lotte (23). What happens once you use a key that has already been declared previously?  

### 2.2 Accessing Data in Dictionaries

**Importance**  
To get the value out of dictionary you pass it the key (just like you use a dictionary: you look up the word and find its definition or translation):

In [123]:
print(student_dict["name"]) 

Lotte


**Let's try it out!**  
Try to get the value of the `study` program. What happens once you pass it a key that does not exist (e.g., `email`)?

Indeed, you get a KeyError if the key does not exist. You can overcome this problem by using `.get()` which returns the value if the key exists and `None` otherwise.

In [139]:
print(student_dict.get("name"))
print(student_dict.get("email"))

Lotte
None


The examples we looked at thus far are relatively straightforward. In reality, there is often a hierarchy of data structures (e.g., a dictionary or list within a dictionary). For example, `enrollments` stores a list of dictionaries with courses. Each course contains a list of students enrolled. 

In [152]:
enrollments = [
    {
        "course": "Online Data Collection & Management",
        "instructor": "Hannes Datta",
        "students": [
            {
                "name": "Lotte",
                "study": "Marketing Analytics",
                "prior_knowledge": True
                
            }, 
            {
                "name": "Joep",
                "study": "Research Master",
                "prior_knowledge": True,
                "honors": "The Societal Challenge of Migration"
            }
        ]
    }
]

**Exercise 4**  
1. Access the `name` key in the `enrollments` list and print the name `Lotte` to the console.
2. Change the key such that it returns the `honors` program of a student enrolled in oDCM. Make sure your code doesn't throw any `KeyErrors`.

In [153]:
# Question 1 
print(enrollments[0]["students"][0]["name"])

Lotte


In [156]:
# Question 2
print(enrollments[0]["students"][0].get("honors"))

None


### 2.3 Adding Elements to a Dictionary

**Importance**  
By now you should be able to handle dictionary keys regardless of whether they are present or not. But how about adding a new key-value pair to a dictionary? 

Contrary to lists, it's not just a matter of appending another item to the end. Rather, you pass the dictionary a key on the left hand-side of the equation and the corresponding value on the right hand-side. 

For example, we can add Lotte's email to the `student_dict` as follows. 

In [159]:
student_dict["email"] = "lotte.v.veen@tilburguniversity.edu"

**Let's try it out!**  
Make sure the `enrollments` stay up to date by also adding Lotte's email there. Can there be an `email` associated with Lotte without any email registered for `Joep`? What happens once you change Lotte's email to `lotte.v.veen@uvt.nl`? 

**Exercise 5**  
Add another `course` (Data Preparation and Workflow Management) taught by Hannes Datta to the `enrollments` list which stores a dictionary with student enrollment data of Sanne, a Marketing Analytics student, with programming prior knowledge.

In [162]:
# solution
enrollments.append({
    "course": "Data Preparation and Workflow Management",
    "instructor": "Hannes Datta",
    "students": [{
        "name": "Sanne",
        "study": "Marketing Analytics", 
        "prior_knowledge": True
    }]
})

### 2.4 Wrap-up
Although dictionaries may look a little daunting at first, we hope you got the hang of it. In future lessons about APIs, you'll see why this data structure is so important for this course. For now, you should have gained the skills to define and access data in dictionaries and argue when a list or dictionary is preferred to store your data. 

---
## 3. Looping

### 3.1 Iterate over items in list

**Importance**  
Naturally, when programming there are a lot of things that you want to repeat. For example, on an ecommerce site you may want to print the description, price, and photo for all products. Then we use a `for` loop to do something with every item in the `iterable_object` (e.g., a list). The `item` references the current position of the iterator, and will run through every item of the collection. 

For example, here we print the price of all items in the list `prices`.

In [88]:
prices = [9.99, 3.95, 24.95]

for price in prices:
    print(price)

9.99
3.95
24.95


**Let's try it out!**  
Add another product price (8.95) to the `prices` list and run the cell again. What happens?

Given the upcoming sales period, you'd like to apply a 10% discount to all your products. Therefore you use a for-loop to update all prices and store it into a new list called `prices_discount`. 

In [89]:
prices_discount = []

for price in prices: 
    price_discount = price * 0.85
    prices_discount.append(price_discount)

print(prices_discount) # in a future lessson we learn you how to round figures!

[8.4915, 3.3575, 21.2075]


**Exercise 6**  
Your manager suggests to change discount policy so that customers are incentivized to buy multiple items. For each additional purchase they receive 10% extra discount on the cheapest item: 
* 1 item = 10% discount 
* 2 items = 20% discount on cheapest item, 10% discount on most expensive item
* 3 items = 30% discount on cheapest item, 20% on second most expensive item, 10% discount on most expensive item, etc.

Write a program that prints out the total price for all products. Your program should work for any number of purchases. Tip: you can sort the list of prices in descending order using `sorted(prices, reverse=True)`.

In [58]:
# solution
total_price = 0
discount_rate = 0.10

prices = sorted(prices, reverse=True)

for price in prices: 
    total_price += price * (1-discount_rate)
    discount_rate += 0.10

print(total_price)

8.0


**Exercise 7**  
We'll continue with the enrollment evaluation program we discussed in exercise 2. More specifically, we provide you with a list of student names, study program, and prior knowledge (`students`), and we'd like you to print a list of all student names who satisfy the course requirements. 

In [79]:
# first name, study, prior knowledge
students = [["Lotte", "Marketing Analytics", True], 
            ["Joep", "Research Master", True], 
            ["Mirte", "Marketing Analytics", False], 
            ["Dirk", "Economics", True], 
            ["Sanne", "Marketing Analytics", True], 
            ["Roy", "Research Master", False]]

# your code goes here!

In [78]:
# solution (most elegant)
for student in students: 
    if student[1] in ["Marketing Analytics", "Research Master"] and student[2]:
        print(student[0])

Lotte
Joep
Sanne


In [81]:
# solution (alternative 1 - iterator)
for student in students: 
    if (student[1] == "Marketing Analytics" or student[1] == "Research Master") and student[2]: # mind the brackets!
        print(student[0])

Lotte
Joep
Sanne


In [82]:
# solution (alternative 2 - counter)
for counter in range(len(students)): 
    if (students[counter][1] == "Marketing Analytics" or students[counter][1] == "Research Master") and students[counter][2]:
        print(students[counter][0])

Lotte
Joep
Sanne


---
### 3.2 Iterate over indices
**Importance**  
Another common strategy to loop over items in a list is to generate a list of indices with the `range()` function. This function returns a sequence of of numbers of which the first number is inclusive and the last number is exclusive. For example, `range(1,10)` generates the numbers 1, 2, ... 9. If you only provide it a single number it assumes you start at zero. 

In [61]:
print(list(range(1,10))) # from 1 to 9
print(list(range(10))) # from 0 to 9

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**Let's try it out!**  
Change the input values and see how it affects your output. What happens if you choose negative values, or if the first value is larger than the second value? 

As said, we use often these counter variables to loop over a list of items. In that case, we generate a sequence of numbers of the same length as the number of items in the list. For example, for `prices = [9.99, 3.95, 24.95]` we use `range(3)` because there are 3 items in the list with index `0`, `1`, and `2`. 

Another way of writing this is `range(len(prices))` which first determines the length of the list of prices (3) and then passes that value to the `range()` function. The advantage is that this method still works if you add (or remove) items from the prices list (so you don't manually need to change it to `range(4)` if you add another price to the list). Note: you don't see the numbers you generated until you use the `list()` keyword.

In [71]:
print(list(range(3)))
print(list(range(len(prices))))

[0, 1, 2]
[0, 1, 2]


Append another item to the `prices` list and run the cell above again. Do both ranges still give the same output? Why (not)? 

---
Next, we combine the concepts of counters and list indexing to loop through all individual elements like this: 

In [74]:
for counter in range(len(prices)):
    print(prices[counter])

9.99
3.95
24.95


**Exercise 8**  
Did you know you that can insert emojis into your code? It works a bit different than you're used to though. You need to pass it a specific [unicode](https://unicode.org/emoji/charts/full-emoji-list.html), for example `\U0001f600` turns into:

In [161]:
"\U0001f600" # in some rare ocassions you may not see a happy emoji below (in that case you can still do this exercise by replacing the emoji by X)

'😀'

That was easy, wasn't it? Here's a challenge for you: use for-loops and counters to construct the following figures (and no: we don't want you to copy paste 100 emojis...): 

<img src="images/smiley.png" align="left" width=20%/>

Here's another one if you're up for it (tip: you need to swap the [unicode](https://unicode.org/emoji/charts/full-emoji-list.html) for another one).

<img src="images/triangle.png" align="left" width=20%/>

In [102]:
# solution
for counter in range(10):
    print("\U0001f600" * 10)

😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀


In [105]:
# solution
for counter in range(10):
    print("\U0001f60d" "" * counter)


😍
😍😍
😍😍😍
😍😍😍😍
😍😍😍😍😍
😍😍😍😍😍😍
😍😍😍😍😍😍😍
😍😍😍😍😍😍😍😍
😍😍😍😍😍😍😍😍😍


---
### 3.3 Iterate over Dictionaries
**Importance**  
Lists on it's own are already iterable, but that's not the case for dictionaries. Yet we can iterate over the `.keys()` and `.values()`. Let's take another look at the `student_dict` dictionary: 

In [164]:
student_dict

{'name': 'Lotte',
 'study': 'Marketing Analytics',
 'prior_knowledge': True,
 'email': 'lotte.v.veen@tilburguniversity.edu'}

In [165]:
for key in student_dict.keys(): 
    print(key)

name
study
prior_knowledge
email


In [166]:
for value in student_dict.values(): 
    print(value)

Lotte
Marketing Analytics
True
lotte.v.veen@tilburguniversity.edu


In practice, you often want to access both keys and values using `.items()`: 

In [131]:
for key, value in student_dict.items(): 
    print(key, value)

name Lotte
study Marketing Analytics
prior_knowledge True


**Exercise 9**  
Given a list of `students_grades` calculate the average grade of all five students. Your code should work properly regardless the number of students (in other words, don't calculate it by hand!).

In [132]:
students_grades = {"Lotte": 6.7, "Joep": 7.2, "Mirte": 9.3, "Dirk": 5.2, "Sanne": 7.5, "Roy": 6.9}
# your code goes here

In [135]:
# solution
total = 0
for value in students_grades.values(): 
    total += value
total/len(students_grades)

7.133333333333334

**Exercise 10**  
In exercise 4 and 5, we looked at a data structure that stores student `enrollments`. We can apply our learnings from this section to easily gather a list of all student names. Write a for-loop to extract all student `names` of *all* courses to a list `students_enrolled`. In other words, make sure your code outputs a list of all student names (even if new courses or students are added).

In [167]:
# solution
students_enrolled = []

for course in enrollments: 
    for student in course["students"]:
        students_enrolled.append(student["name"])
    
print(students_enrolled)

['Lotte', 'Joep', 'Sanne']


---
## 4. Functions

### 4.1 Syntax

**Importance**  
Without realizing it, you have already used plenty of Python functions: `print()`, `len()`, `range()` just to name a few. Formally, a function is process for executing a task which, simply put, is a bunch of lines of code wrapped up in a package that you can reuse. In other words, it's useful for executing similar procedures over and over. This helps  your code to stay DRY (Don't Repeat Yourself) which is a software development principle to keep your code clean and prevent code duplication. 

For example, let's say you a `book_price_usd`, `tablet_price_usd`, and `laptop_price_usd` variable that stores the product price in dollars, which you'd like to convert to euros. Then you could repeat yourself 3 times in a row, like this: 

In [180]:
book_price_usd = 19
book_price_eur = book_price * .82 
print(f"The price in euros is {book_price_eur}")

tablet_price_usd = 349
tablet_price_eur = tablet_price_usd * .82 
print(f"The price in euros is {tablet_price_eur}")

laptop_price_usd = 699
laptop_price_eur = laptop_price_usd * .82 
print(f"The price in euros is {laptop_price_eur}")

The price in euros is 15.579999999999998
The price in euros is 286.18
The price in euros is 573.18


But what if the USD-EUR exchange rate changes to `.83` tomorrow? Then, we need to update our code on 3 places. Now, imagine what would happen if we were to keep track of the prices of thousands of products... It would take ages! For that reason, it's recommended to not repeat yourself. Functions help a great deal with that. 

Each function starts with `def` followed by the name of the function (usually in snake_case = words separated by underscores; you can give it any name you like!), parentheses `()`, and a colon (`:`). Like if-statements, the next code block is indented. 

You can invoke the function by calling the name of the function followed by parentheses, for example:

In [182]:
def sing_happy_birthday(): 
    print("Happy Birthday To You")
    print("Happy Birthday To You")
    print("Happy Birthday Dear You")
    print("Happy Birthday To You")

sing_happy_birthday()

Happy Birthday To You
Happy Birthday To You
Happy Birthday Dear You
Happy Birthday To You


**Let's try it out!**  
Call the function `sing_happy_birthday()` three more times. Do you see how just three lines of code create another 12 print statements? 

---
### 4.2 Variable Scope
**Importance**  
Within a function you can assign variables like you're used to. It's, however, important to realize that variables created in functions are scoped in that function. That is to say, you can only refer to these variables inside the body of the function. For example, the `print(instructor)` statement will raise an error. 

In [1]:
def say_hello():
    instructor = "Hannes"
    print("Hello " + instructor)
    
say_hello()
print(instructor) 

Hello Hannes


NameError: name 'instructor' is not defined

**Let's try it out!**  
Change the location of the `instructor` variable such that you solve the `NameError`. Does the `say_hello()` function also have access to the `instructor` variable? 

---
### 4.3 Parameters
**Importance**  
Most functions accept input, perform some transformation, and then output the result. Parameters are temporary input variables you can use within the function. You can think of them as placeholders that get assigned when you call the function. You can name parameters anything you want but it's recommended to use semantic names (that have a meaning). For example, not `string1` but `first_name`. Below the function `say_hello()` takes a single parameter `first_name` that is used within the body of the function. 


In [4]:
def say_hello(first_name):
    print("Hello " + first_name)
    
say_hello("Hannes")

Hello Hannes


**Let's try it out!**  
Call the function `say_hello()` with your own name. Add a second parameter `last_name` and adapt the function such that it prints the full name (first and last name combined). 


By default the function assumes that the first argument (e.g., `"Hannes"`) corresponds with the first parameter (`first_name`). If you'd like to change the order you need to explicitly specify that as follows: 

In [10]:
def say_goodbye(greeting, person):
    print(greeting + " " + person + "!")
    
say_goodbye(person = "Mom", greeting = "Love you")
# say_goodbye("Mom", "Love you") assumes that greeting = "Mom", person = "Love you"

Love you Mom!


---
### 4.4 Return Keyword
**Importance**   
Rather than solely printing some text to the console, you often want to store the output of a function in another variable which is exactly what the `return` keyword does. It literally "returns" the output which can be a single variable, but also a list or dictionary. In the example below we add up `a` and `b` and store the outcome in another variable `result`. 




In [13]:
def add(a,b):
    return a + b

result = add(3,4)
print(result)

7


**Let's try it out!**  
Use your new function to add up the numbers `5` and `-2`. Can you reuse the result (3) in another `add()` function? 


**Exercise 11**  
Write a function called `return_day()` that takes one parameter (a number from 1-7) and returns the day of the week (1 = Monday, 2 = Tuesday, etc.). If the number is less than 1 or greater than 7 the function should return None. 

In [23]:
# solution
def return_day(num):
    days = {1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday", 5: "Friday", 6: "Saturday", 7: "Sunday"}
    return days.get(num)

print(return_day(0))
print(return_day(1))
print(return_day(2))
print(return_day(8))

None
Monday
Tuesday
None


It's important to realise that once a program reaches a `return` statement, it exits the function immediately. The `convert_usd_eur()` function takes a list of `usd_amounts` and calculates the equivalent amount in euros. Note that input list includes 3 amounts, but the output has only a single value. Why is that? 

In [24]:
def convert_usd_eur(usd_amounts, currency_rate):
    eur_amounts = []
    for usd_amount in usd_amounts: 
        eur_amounts.append(usd_amount * currency_rate)
        return eur_amounts
        
convert_usd_eur([10, 100, 1000], .82)

[8.2]

**Let's try it out!**   
The `return` statement is indented twice so that it exits the function in the first loop ($10), rather than after the third iteration. Fix the code so that it works as expected. 

**Exercise 12**  
Write a function `add_list()` that adds up all numbers in `num_list` and returns the `total` value. Test your function with the following list `[3, -4, 1, 2, 0]`.

In [15]:
# solution
def add_list(num_list):
    total = 0
    for num in num_list: 
        total += num
    return total

add_list([3, -4, 1, 2, 0])        

2

### 4.4 Documentation
**Importance**   
For built-in functions (e.g., `print()`) you can directly access its documentation by moving your cursor to the function and pressing `Shift` + `Tab` at the same time (doing it twice collapses the menu). You can also add documentation to your own functions with a so-called docstring: put a triple quote (`"""`) at the start of your function and write a brief description. Then, once you press Shift + Tab in your newly created function (e.g., `add()`) the doc-string will appear in the pop-up. 

<img src="images/docstrings.gif" align="left" width=60%/> 

**Let's try it out!**  
Inspect the documentation of `range()` and `len()`, and add an appropriate docstring to the `convert_usd_eur()` function above. 

### 4.5 Wrap-up
Functions are procedures for executing code. They accept inputs and return outputs when the return keyword is used. You can write our own functions, use built-in functions, or - as you'll find out later - import packages to use functions written by others. 

---
## 5. Debugging & Error Handling

### 5.1 Types of Errors

**Importance**  
More likely than not, you have run into some error up to this point. Then you'll know that it breaks the entire application: all lines after the error will not be executed. To catch errors so that the program still runs, we use `try` and `except` blocks. But first let's take a quick look at the most common errors: 

| Error | Meaning | Example | Explanation |
| :-- | :-- | :-- | :-- |
| `SyntaxError` | Incorrect syntax (e.g., a typo) | `print("hello"` | Missing the closing `)` |
| `NameError` | Variable is not assigned | `print(undeclared_variable)`| `undeclared_variable` has not been defined |
| `TypeError` | Mismatch of data types | `"My age is " + 23`| You cannot mix integers and strings |
| `IndexError` | Invalid index in a list | `some_list = []` <br> `some_list[2]` | Index 2 does not exist in an empty list | 
| `ValueError` | Right type of input but <br> an inappropriate value | `int("hello")` | It expects a number formatted as string (e.g., `"8"`).|
| `KeyError` | Dictionary does not have <br> a specific key | `some_dict["missing_key"]` | `missing_key` is not defined in `some_dict`.|

**Let's try it out!**  
For each of the code blocks below figure out the type of error (you can check yourself by running the code!)

### 5.2 Try and Except Blocks

**Importance**  
Let's have another look at the `convert_usd_eur()` function which we pass a list of both numeric and string data. As a result, the function breaks once it reaches `"18,82"` returns a `TypeError`. In other words, it did not convert `3049.49` dollars to euros even though it is in the right numeric format. Instead, it would be preferred to skip over the wrong value (`"18.82"`) and continue with the subsequent values. 


In [53]:
def convert_usd_eur(usd_amounts, currency_rate):
    eur_amounts = []
    for usd_amount in usd_amounts: 
        eur_amounts.append(usd_amount * currency_rate)
    return eur_amounts
        
convert_usd_eur([9.95, "18,82", 3049.49], .82)

TypeError: can't multiply sequence by non-int of type 'float'

We can overcome this issue by checking (`try`) whether the multiplication (`usd_amount * currency_rate`) is valid. If so, it will perform the operation like we did previously. If not, it moves on to the `except` block in which we can describe how to handle the error (e.g., print a custom error message): 

In [54]:
def convert_usd_eur(usd_amounts, currency_rate):
    eur_amounts = []
    for usd_amount in usd_amounts: 
        try: 
            eur_amounts.append(usd_amount * currency_rate)
        except: 
            print(f"The value {usd_amount} is invalid")
    return eur_amounts
        
convert_usd_eur([9.95, "18,82", 3049.49], .82)

The value 18,82 is invalid


[8.158999999999999, 2500.5817999999995]

**Let's try it out!**  
Note that the function output only contains 2 values (the EUR amount of `$9.95` and `$3049.49`). What happens once you pass `convert_usd_eur()` a single value rather than a list? And how about a list of booleans? 

**Exercise 13**  
Revise the function `return_day()` (Exercise 11) such that it returns the error message `"Please enter a number between 1 and 7"` when invalid input has been inserted (rather than `None`). 

In [71]:
# solution
def return_day(num):
    days = {1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday", 5: "Friday", 6: "Saturday", 7: "Sunday"}
    try: 
        return days[num]
    except: 
        return "Please enter a number between 1 and 7"

print(return_day(0))
print(return_day(1))
print(return_day(2))
print(return_day(8))

Please enter a number between 1 and 7
Monday
Tuesday
Please enter a number between 1 and 7


* Naturally when programming there are a lot of things that you want to repeat. 
* Print numbers 1 to 7 manually -> vervolgens automatiseren
* Webshop voorbeeld: in plaats voor elk object: print name, print price, etc. 
* "for" refers to the idea that you want to do something for every item  in the list (or a number in a range) 
* for item iterable_object: 
    do something with item 
    * iterable object is some kind of collection of items (e.g., list of numbers, a string of characters, a range)
    * item is a new varible that can be called whatever you want
    * item references the current position of our iterator within the iterable. It will iterate over (run through) every item of the collection and then go away when it has visited all items. 
* range is a way of quickly generating sequences of numbers 
    * first number is inclusive, last number is exclusive: range(1,8) is 1 to 7 
    * if you only provide 1 number it assumes you start at zero (range(8))
    * you don't see the numbers you generated until you use the `list()` keyword
    
* while loops
    * every thing you can do with a for loop you can do with a while loop (but the while loop has some options - inherent if statement)
        * while loops require more careful setup than for loops since you have to specify the termination condition manually 
    * starts with a boolean expression 
    * anything in the loop will run as long as the boolean expression is True (while loops continue to execute while a certain condition is truthy, and will end when they become falsy) 
    * while im_tired: #seek caffeine
    * user_response = None
      while user_response != "please": 
          user_response = input("Ah ah ah, you didn't say the magic word")
    * be careful! if the condition doesn't become false at some point, your loop will continue forever! (= infite loop) 
    * msg = input("what's the secret password?")
      while msg != "bananas":
        print("WRONG!"
        msg = input("what the secret password?")
      print("CORRECT!")
    * while loops are more flexible 
    * for loops - if you want to run something a set number of times + shorter to write 
      
* convert a for loop to a while loop
    * for num in range(1,11): print(num)
    * num=1, while num < 11: print(num) num += 1
    
* break keyword 
    * The keyword `break` gives us the ability to exit out of while loops whenever we want
    * while True: 
        command = input("Type exit to exit: ") 
        if command == "exit": 
            break 
    * it breaks out immediately 
        * for time in range(times): 
            break 
            print("AADSFASDF") # deze zin doet hij niet eens





* We can use these comparisons as input for our if-statements

* 
    * If-statements represents different paths a program can take based on some type of comparison of input 
        * if some condition is True: 
            * do something
        * elif some other condition is True: 
            * do something
        * else: 
            * do something

        * Can be more than 1 elif
        * Need the colons (:) - indicator there will be an indented block below 
        * Note the indentation (TAB or 4 spaces)  
            if name == "abc":  
            print("gives an error")
           
 
* Logical operators
    * if bachelor == ... or bachelor == ... : (diagram maken of ze worden toegelaten tot de opleiding) 
    * price of ticket depending on your age, student card, etc.
    * haakjes combineren (a and b) or c: 
        * Exercise: put parentheses around different logical statements to make it easier to break down 



In [ ]:
if balance < 0: 
    print("You should top up your checking account to avoid paying interest")
elif balance == 0: 
    print("Your checking account balance is exactly €0.00, be careful when making new payments!")
else: 
    print("You have a positive balance")

### 1.3 And / Or Operators

## 1. Jupyter Notebooks


### 1.1 Opening Files
* From local disk user directory
* From a download in user directory 

### 1.2 Code & Markdown
* Code 
    * `print("...")`
    * `print()` statements in Python files vs Jupyter Notebooks
    * Multiple operations below one another 
* Markdown 
    * Headers, regular text, italics, bold
    * Nieuwe regel (2x spatie) 
    * Bullet points and numbered lists
    * Inline code

* Run cells
* Add new cells or remove existing cells 
* Moving cells up or down


### 1.x Documentation
https://docs.python.org/3.8/library/index.html
Stackoverflow 
Python 2 docs longer around but not always up to date / syntax changes (e.g., print X


## 2. Variables 
* Understand how to assign and use variables 
* Learn Python variable naming restrictions and conventions 
* Learn and use some of the different data types available in Python
* Understand how to convert data types (string to number) 

### 2.1 Introduction
* A variable in Python is like a variable in mathematics: it is a named symbol that holds a value 
    * Variable name on the left; value on the right of the equal sign
    * Reusability (a very long number that you don't want to type out every time) 
    * Dynamic data (it can take on different values) 
    * Variables must be assigned before they can be used
    * Input for user input 
    * page_num = 1
        * recall: page_num -> gives 1
        * page_num = page_num + 1 -> 2
        * reassign values: page_num = 10 (overschrijft alle waarden tot dan toe) 
    
    
### 2.2 Naming conventions
* Must start with a letter or underscore (dus niet: 24_opening_hours = "00:00 - 23:59"; maar my_1st_variable is weer wel goed) 
* The rest of the name must consist of letters, numbers, or underscores (geen @ - odcm@uvt.nl) 
* Names are case-sensitive (course_name != Course_Name) 

* Convention: guidelines/style - what most people should do
    * Variables should be snake_case (underscores between words) 
        * Exercise: rewrite code so that it matches Python conventions
    * Variables should be also be lowercase (tenzij het echt een constante is: PI = 3.14)
        * UpperCamelCase (refers to a class)
        * lower_snake_case
        * UpperCamelCase
        * CAPITAL_SNAKE_CASE
        * lower-dash-case
        
        
### 2.3 Comments
* Add comments to your code (shortcut: Cmd + /)
    * Markdown comments
    * Code comments
    * Multiline comments
    * Especially if you're starting out; code is not always self-explanatory
    * If you're working in a team 
    * Comment part of your code (rather than deleting it - to test other parts of the code) 

        
## 3. Data Types

| data type | description | 
| :--- | :---|
| bool | True or False values |
| int | an integer (1,2,3) |
| str | (string) a sequence of characters ("Roy") |
| list | an ordered sequence of values of other data types, e.g. [1,2,3] or ["a", "b", "c"]
| dict | a collection of key: values, e.g. {"first_name": "Colt"}


* Strings
    * String literals can be declared with either single or double quotes
    * Inside single (') or double (") quotes
    * It's up to you what you prefer, but stick to the same convention throughout the same file 
    * It's really just a stylistic thing - equivalent to each other if you compare them 
    * Doesn't really matter but you have to be consistent
    * Use quotes inside quotes: "he said "hello there!""
        * 'he said: "hello there!"'
        * "he said: \"hello there!\"
    * new_line = "hello \n world!" (wordt verdeeld over meerdere regels; ziet het alleen bij een print-statement)
    * type(8) vs type ("8")
    * len("some text") 
    * String concatenation
        * = putting two strings together
        * str_one = "your", str_two = "face", str_three = str_one + " " + str_two 
        * print("Hello there and welcome to the game, " + username)
            * greeting = None
            * name = None
            * greet_name = greeting + " " + name
        * Different data types
            * 8 + "hello" -> TypeError
    * f-strings
        * x = 10 
        * formatted = f"I've told you {x} times already!"
        * takes what inside the {} and turns it into a string
    * Indexing
        * Indices always start at 0 in Python (contrary to R)
        * Index out of range
        * variable[len(variabley) - 1]
        
        
* Integers
    * Understand difference between ints and floats
    * Decimal number takes up much more space
    * `type(9)` vs `type(9.0)`
    * 1 + 1.0 = 1.0 (int + float = float) 
    * ** = exponentiation, % = modulo, // = integer division
    * order of operations 
    * pemdas (parentheses, exponents, multiplication, division, addition, subtraction)   

* None 
    * Not a string
    * Starts with a capital "N"
    * Way for Python to express the concept of "nothing"
    * Example: name = "Daisy", age = 30, child = None (in plaats van het helemaal weg te laten beter om expliciet te zeggen None - want a container for the variable ) 
       

                
## Looping in Python
* Naturally when programming there are a lot of things that you want to repeat. 
* Print numbers 1 to 7 manually -> vervolgens automatiseren
* Webshop voorbeeld: in plaats voor elk object: print name, print price, etc. 
* "for" refers to the idea that you want to do something for every item  in the list (or a number in a range) 
* for item iterable_object: 
    do something with item 
    * iterable object is some kind of collection of items (e.g., list of numbers, a string of characters, a range)
    * item is a new varible that can be called whatever you want
    * item references the current position of our iterator within the iterable. It will iterate over (run through) every item of the collection and then go away when it has visited all items. 
* range is a way of quickly generating sequences of numbers 
    * first number is inclusive, last number is exclusive: range(1,8) is 1 to 7 
    * if you only provide 1 number it assumes you start at zero (range(8))
    * you don't see the numbers you generated until you use the `list()` keyword
    
* while loops
    * every thing you can do with a for loop you can do with a while loop (but the while loop has some options - inherent if statement)
        * while loops require more careful setup than for loops since you have to specify the termination condition manually 
    * starts with a boolean expression 
    * anything in the loop will run as long as the boolean expression is True (while loops continue to execute while a certain condition is truthy, and will end when they become falsy) 
    * while im_tired: #seek caffeine
    * user_response = None
      while user_response != "please": 
          user_response = input("Ah ah ah, you didn't say the magic word")
    * be careful! if the condition doesn't become false at some point, your loop will continue forever! (= infite loop) 
    * msg = input("what's the secret password?")
      while msg != "bananas":
        print("WRONG!"
        msg = input("what the secret password?")
      print("CORRECT!")
    * while loops are more flexible 
    * for loops - if you want to run something a set number of times + shorter to write 
      
* convert a for loop to a while loop
    * for num in range(1,11): print(num)
    * num=1, while num < 11: print(num) num += 1
    
* break keyword 
    * The keyword `break` gives us the ability to exit out of while loops whenever we want
    * while True: 
        command = input("Type exit to exit: ") 
        if command == "exit": 
            break 
    * it breaks out immediately 
        * for time in range(times): 
            break 
            print("AADSFASDF") # deze zin doet hij niet eens
    



## Lists


## Dictionairies

## Functions

## Modules

## Error Handling

## Reading Text Files




## Data Structures
* Store other data types inside of them -> data structures

* List
    *  

* Dictionary 
    * There is no order
    * Pairs 

    
    

    
    

In [14]:
# print the following beautiful art using both a for loop and while loop
# if the emoji doesn't print on your machine use a hash or a star 
print("\U0001f600")
print("\U0001f600 \U0001f600")

😀
😀 😀


In [17]:
for num in range(1,11):
    print("\U0001f600" * num)

😀
😀😀
😀😀😀
😀😀😀😀
😀😀😀😀😀
😀😀😀😀😀😀
😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀


In [19]:
# nested for loops (als je dat gehele ding 3x onder elkaar wilt hebben)

num = 1

while num < 11: 
    print("\U0001f600" * num)
    num += 1

😀
😀😀
😀😀😀
😀😀😀😀
😀😀😀😀😀
😀😀😀😀😀😀
😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀
😀😀😀😀😀😀😀😀😀😀


---

## 1. Numbers, Operators, and Comments





    


In [5]:
9//2

4

--- 

## 2. Jupyter Notebook

* Starting up Jupyter Notebook
    * Anaconda Navigator (but: starts up in user directory)
    * Via Anaconda Terminal: learn how to navigate the command line (directory structure, pwd, cd, ls, relative/absolute file paths)
  
* Installing Python packages
    * Anaconda Terminal (vs pip install)
    
* Using the Anaconda interface
    * Opening files 
        * From local disk (user directory)
        * From a download from the internet, in user directory
        * From another directory on the computer
    * Run cells (control flow from top to bottom)
    * Interactivity allows for instant feedback
    * Add new cells or remove existing cells 
    * Moving cells
    * Run cells (`Shift + Enter`) 
    
* Writing markdown cells
    * Headers, regular text, italics, bolds
    * Links / images
    * Bullet points and lists
    * Inline code
   
* Getting help
    * Stackoverflow
    * Help [...]


## 3. Python Fundamentals
* Data types
    * Define numeric, string, and boolean variables
        * Integers and floats
        * Double vs single quotes (strings)
        * Escape sequences
    * Write inline and multiline comments 
    * Convert variables into different type
    * Math operations (+, -, *, /, mod) 
    * String operations (concatenate, replace, join, .lower(), .upper()) 


* Data structures
    * Create a list (with different data types)
    * Slicing a list 
    * Iterating over lists
    * Extending list elements (append)
    * Create a dictionary 
    * Return values by passing keys
        * Nested dictionairies
        * .get() vs ['key'] 
    * Adding items to dictionary


* Conditional logic
    * If-else statements
    * Multiple elifs
    * Logical and & or |
    * Logical not (!, not)
    * Comparisons (== and =)


* Looping
    * Loop using counter (range)
    * Loop over list elements
    * Looping over dictionary at different “levels” (keys and values)


* Functions 
    * Parameters
    * Return keyword
    * Scope 
    * Docstrings


* Modules
    * Installing modules
    * Importing modules 
    * Selective imports (from … import ... ) 
    * Aliasing modules (as …)
    * Look up documentation (help statement)


* HTTP requests
    * HTTP verbs (get, post)
    * Requesting JSON
    * JSON formatter plugin


* Debugging and error handling
    * Common types of errors
    * Try and except blocks
    * Else and finally


* Files
    * Open and read text files
    * With statements
    * Writing to text files

* https://github.com/kimfetti/Conferences/tree/master/PyCon_2020
* https://www.youtube.com/watch?v=RUQWPJ1T6Zc&t=190s
* https://github.com/hancush/web-scraping-with-python/blob/master/session/web-scraping-with-python.ipynb#HTML-basics
* https://www.udemy.com/course/the-modern-python3-bootcamp/learn/lecture/7991196#overview
* https://campus.datacamp.com/courses/web-scraping-with-python/introduction-to-html?ex=1
* https://realpython.com/python-web-scraping-practical-introduction/
* https://github.com/CU-ITSS/Web-Data-Scraping-S2019