---
title: "Exam preparation (week 6)"
subtitle: "Online Data Collection & Management (2025/2026)"
author: "Hannes Datta"
date: "last-modified"
format: 
    beamer:
      theme: metropolis
      colortheme: seahorse
      linkcolor: blue


---

## Agenda

1. Exam setup
2. Example questions
3. Q&A

## Exam Setup

- 120-minute on-campus computer exam (328060-M-6; 180 minutes for 328060-M-3) - __let's verify enrollment__
- "Closed-book" exam
  - __with__ internet
  - access to the code of all tutorials and auxilary resources posted on Canvas (Python bootcamp, web scraping 101/adv., API 101/adv., computer infrastructure)
  - one cheat sheet allowed (details will follow)
- Two exam dates per academic year (in block 2)

## Exam Format

- **Mix of open and closed questions** (e.g., multiple-choice, ranking (e.g., from low to high, high to low), matching items)
- **120 points total** (~1 point per minute)
- **Questions aligned with learning goals** (tutorials, lectures, slides, code posted to Canvas, papers/readings)

## Cognitive Skills

*Bloom’s Taxonomy of Learning Objectives*

- **Knowledge**: Recall key concepts 
- **Comprehension**: Demonstrate understanding of key concepts
- **Application**: Use techniques to solve new problems
- **Analysis**: Break down and solve complex tasks (e.g., using datasets, workflows)
- **Evaluation**: Critically judge suitability of approaches or compare solutions
- **Synthesis**: Combine elements (data, code, interpretation) into coherent results

## Overview of Questions

| No. | Learning goal | Evaluation Level | Question Type | Points |
|---|------------------------|-------------|------|-----|
| 1 | Explain web data in academic literature  | Comp. | MC | 12
| 2 | Select web data sources and evaluate value | Knowledge & Eval. | MC & Open | 24
| 3 | Design collections balancing V/TF/LER | MC & Open | 24
| 4 | Collect data with scraping/APIs | Applic. & Synthesis | Coding | 48 |
| 5 | Document & archive for public (re)use | Knowledge | MC | 12 |
|   | Total  | | | 120

# Preparing for the Exam

## Familiarize yourself with TestVision

- Take the **technical practice exam** (access via [https://tiu.nu/testvision](https://tiu.nu/testvision))
  - learn how to upload & download files
  - understand how to unzip repositories, and rezip them for file submission
  - see how to fill in answers into text boxes and view the word count
  - get a general understanding of how TestVision works
- Additional resources
  - Explore [TestVision’s generic practice exam](https://oefentoetsen.testvision.nl/online/fe/login_ot.htm?campagne=tlb_demo_eng&taal=2).
  - Review [Tilburg University’s TestVision resources](https://www.tilburguniversity.edu/students/studying/exams/e-assessment/testvision).

## Technical Tips

- **Exam environment**:
  - Practice using **Windows**, RStudio, and the command prompt (__not__ PowerShell; ideally Anaconda Prompt, sometimes GitBash).
- **File management**:
  - Organize files by question in local folders (e.g., `C:\Users\<YOUR-U-NUMBER>\Downloads`).
  - Know how to open `.ipynb` files 
  - Zipping (before uploading) / unzipping (when downloading)
  - Revise code for clean (top-down!) execution. No useless code.
- **Use of the Inspect Mode**
  - Inspect mode not available in Edge; __use Chrome__ (installed)

## Cheatsheets

- **Collective cheatsheet**
  - Drafted collaboratively in Google Docs, reviewed by the instructor, and shared as PDF.
  - [Link to the document](https://docs.google.com/document/d/1-Wm94h54ftJ8NDIHAbFoB-O3LeEF4eGlM_xi1delzUs/edit?usp=sharing)
  - Deadline to make your changes: 10 December 2025, 1pm.
  - I will review the document, make changes where required, and add it to the Cheatsheets.

## TestVision’s Introduction Page

- Every exam begins with an **introduction/cover page** containing official instructions.
- I will show you example cover pages now...
- Review in advance: The cover page will be available on Canvas before the exam

## Questions so far?

## Next steps

- Course evaluation
- Closing lecture next week
- Final coaching session (Roshini)

<br>
Thanks!