---
title: "Overview"
format: html
number-depth: 1
---

## Learning Goals

Collecting data via web scraping and APIs requires practice. Together with your team members, you plan and execute an online data collection throughout the course by closely following class content and readings.

At the end of the course, you will submit a data package, consisting of:

- Your collected data
- All source code
- A documentation ("readme") 


<!--(following [this template](Datasheets_for_DataSets.zip))-->

<!--For inspiration, explore [past team projects](pastprojects). Use these as a starting point, keeping in mind that grading criteria may have changed and these examples are not flawless.-->

::: {.callout-note}
The focus lies on completing an entire data collection project. Keep each stage of your project manageable and feasible. Your project will ultimately be written up as a proper data documentation (readme), following [this paper](https://arxiv.org/pdf/1803.09010.pdf) and corresponding [template download](Datasheets_for_DataSets.zip). Ensure to also check the grading details.
:::


## Organization


### Coaching sessions

During the course, you will have the opportunity to meet up with the course instructor for coaching sessions. These sessions are meant for you to receive feedback on your ideas and code. Frequently, this also entails problem-solving & debugging.

- **Participation:** All teams attend the full session. Teams typically collaborate on their projects while the course instructor provides support (in-person by walking around or via Zoom breakout rooms).
- **Session Format:**
  - First Half: Each team gets 5–10 minutes to provide a progress update and seek assistance from the coach.
  - Second Half: Time is allocated on a needs basis to address specific issues or questions raised by teams.
- **Weekly Deliverables:** 
  - Most coaching sessions will help the team work on some deliverables, which are always due before the next coaching session. 
  - Deliverables are submitted on Canvas. Please check Canvas for the due dates for each week. 
  - The course team will provide short feedback in line with the grading rubric, at least a day before the next coaching session.

::: {.callout-note}
**How to Prepare for Coaching Sessions?**

1. **Complete Weekly Tasks:** Work on your project and submit weekly deliverables to receive constructive feedback.
2. **Preparation:** Review lecture materials and relevant academic literature (e.g., Boegershausen et al., 2022; Guyt et al., 2024).
3. **Solve Technical Issues:**
   - Check for solutions on Canvas, as well as [YouTube](https://www.youtube.com/playlist?list=PLdDbyJQwReWhis9Ns7_NfYzw4YAp91D6G) or [YouTube channel](https://youtube.com/c/hannesdatta).
   - Perform your own research using the course chatbot or Google/StackOverflow.
4. **Set Up Jupyter Notebook:**
   - Load scripts and display any issues (e.g., error messages) on your screen for troubleshooting. Screenshots alone are insufficient.
5. **For Online Sessions:**
   - Share your screen (Jupyter Notebook) and ensure your microphone is functional.
   - Be ready for the instructor to take over your screen if needed.
:::


### Timeline

- The project teams are finalized in week 2 and must be registered on Canvas.
- You start working on your project in week 3.
- Coaching sessions start from week 4 onwards.

### Team composition

- 4-5 students per team
- Enroll your team on Canvas by week 3 (project starts in week 4)

### Submission

- Deadline: 5 December, 2025 (23:59)
- Submission of your data package on Canvas in one zip file.

### Permitted Level of AI Use

__Level of AI allowed for this assignment:__ AI-assisted idea generation and structuring (Level 3 on AI Index Tilburg University)

::: callout
- You are allowed to use generative AI tools to develop or refine initial ideas, materials, paraphrasing, structures, or outlines. This includes generating code, e.g., for R.
- Failing to declare AI use, or using AI beyond what is allowed in the syllabus, may be considered fraud and will be reported to the Examination Board.
- Mandatory for students: For this assignment, please keep a simple “logbook” documenting which AI tools you have used and for what purposes. Submit this logbook with the assignment (e.g., as a PDF). Examiners may inspect the logbook at any time. Failing to declare AI use, or using AI beyond what is allowed in the syllabus, may be considered fraud and will be reported to the Examination Board.
:::

<!--
## Getting started

- [Workplan, deliverables, and coaching](workplan)
- [Grading requirements](grading)
- [Past projects](pastprojects)
- [Tips and examples](examples)

## Organization
-->

